name: main

on:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: erlef/setup-beam@v1
        name: Prepare BEAM
        with:
          otp-version: "26.2"
          gleam-version: "1.1"

      - uses: denoland/setup-deno@v1
        name: Prepare Deno
        with:
          deno-version: v1.x

      - run: gleam format --check
        name: Format

      - run: gleam test
        name: Test

      - run: gleam build
        name: Build

      - uses: actions/upload-artifact@v4
        name: Package
        with:
          name: gleam-build
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: actions/download-artifact@v4
        name: Fetch latest build
        with:
          name: gleam-build
          path: build/

      - run: echo "main();" >> ./build/dev/javascript/deno_deploy_template/deno_deploy_template.mjs
        name: Prepare entrypoint

      - uses: denoland/deployctl@v1
        name: Deploy
        with:
          project: nakai-template
          entrypoint: ./build/dev/javascript/deno_deploy_template/deno_deploy_template.mjs
